repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: pretty-format-json
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.2"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
      - id: mypy
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: "v1.0.6"
    hooks:
      - id: shell-lint
        args: [--format=json]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v3.2.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/mrtazz/checkmake.git
    rev: "0.2.2"
    hooks:
      - id: checkmake
  - repo: https://github.com/gitleaks/gitleaks
    rev: "v8.18.2"
    hooks:
      - id: gitleaks
  - repo: https://github.com/google/yamlfmt
    rev: "v0.11.0"
    hooks:
      - id: yamlfmt
  - repo: https://github.com/rhysd/actionlint
    rev: "v1.6.27"
    hooks:
      - id: actionlint
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.2"
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
