name: "Stale"
on:
  schedule:
    - cron: "30 1 * * 0"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: >
            "This issue has been automatically marked as stale because it has not had recent activity.  It will be closed if no further activity occurs."

          stale-pr-message: "This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 21 days."
          close-issue-message: "This issue was closed because it has been stalled for 14 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 21 days with no activity."
          days-before-issue-stale: 60
          days-before-pr-stale: 45
          days-before-issue-close: 14
          days-before-pr-close: 21
          exempt-issue-labels: pinned, security
          exempt-pr-labels: pinned, security
